<?php

########################################################################
# Extension Manager/Repository config file for ext: "bb_userlist"
#
# Auto generated by Extension Builder 2011-08-18
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MM_Forum Userlist',
	'description' => 'A ExtBase / Fluid Userlist for mm_forum',
	'category' => 'plugin',
	'author' => 'Bastian Bringenberg',
	'author_email' => 'typo3@bastian-bringenberg.de',
	'author_company' => 'Bastian Bringenberg',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>